### ISSUE TITLE
Can't "make all" in quorum

### ISSUE THREAD

**Issue by PopCloud97** [jpmorganchase/zsl-q#10]
To "Build quorum and copy binaries into a folder in the quorum-examples project"
when I "make all" in /projects/quorum it ends with:

github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp
........................
github.com/ethereum/go-ethereum/internal/guide
util.go:44: exit status 2
exit status 1
Makefile:29: recipe for target 'all' failed
make: *** [all] Error 1

It's so aburpt.  My go version is 1.7.3.    What's going wrong?

**Comment by fixanoid** [comment]
Are you building it in quorum-examples vagrant guest environment or on the host?

**Comment by PopCloud97** [comment]
My host OS is win10 so I built it in VMware 15, Ubuntu 16.04.
...Maybe because of this?

**Comment by fixanoid** [comment]
Building has to be done in the vagrant quorum-examples off this: https://github.com/jpmorganchase/quorum-examples/tree/zsl_geth1.6

**Comment by fixanoid** [comment]
You may be able to build directly in the Ubuntu as well, but then you need your own version of this config:  https://github.com/jpmorganchase/quorum-examples/blob/zsl_geth1.6/vagrant/bootstrap.sh

**Comment by PopCloud97** [comment]
Very helpful. Thanks!
