### ISSUE TITLE
Not able to compile binaries

### ISSUE THREAD

**Issue by collins4technology** [jpmorganchase/zsl-q#4]
Hi,

Getting the below error when executing the first step of the setting up document.

cd vendor/github.com/jpmorganchase/zsl-q/zsl-golang/zsl/snark/ ; make
make[1]: Entering directory `/home/vagrant/quorum/vendor/github.com/jpmorganchase/zsl-q/zsl-golang/zsl/snark'
g++ -o zsl.o -x c++ impl.tcc -c -g -Wall -Wextra -Wno-unused-parameter -std=c++11 -fPIC -Wno-unused-variable -I./libsnark/ -I./libsnark/src/ -DCURVE_ALT_BN128 -DBINARY_OUTPUT -DMONTGOMERY_OUTPUT -DNO_PT_COMPRESSION=1 -DMULTICORE -fopenmp -DNO_PROCPS -march=native -mtune=native -O2
In file included from ./libsnark/src/relations/variable.tcc:23:0,
                 from ./libsnark/src/relations/variable.hpp:211,
                 from ./libsnark/src/gadgetlib1/pb_variable.hpp:15,
                 from ./libsnark/src/gadgetlib1/protoboard.hpp:16,
                 from ./libsnark/src/gadgetlib1/gadget.hpp:11,
                 from ./libsnark/src/gadgetlib1/gadgets/basic_gadgets.hpp:14,
                 from impl.tcc:18:
./libsnark/src/algebra/fields/bigint.hpp:14:17: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
                 ^
compilation terminated.
make[1]: *** [all] Error 1

Thank you in advance.

Regards,
Collins

**Comment by fixanoid** [comment]
Should have been pulled down with libdev fetch, but if not, try yum install  libgmp3-dev or apt-get install  libgmp3-dev
